# Generated by Django 4.0.4 on 2022-04-20 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personalblog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='title_tag',
            field=models.CharField(default='Ludmila Ceriani', max_length=255),
        ),
    ]
