# Generated by Django 4.0.4 on 2022-05-27 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personalblog', '0007_post_header_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='snippet',
            field=models.CharField(default='Clik Link Above To Read Blog Post...', max_length=255),
        ),
    ]
